INSERT INTO dogs (
    name,
    breed,
    supplier,
    badge_id,
    gender,
    birth_date,
    date_acquired,
    current_status,
    leaving_date,
    leaving_reason,
    kennelling_characteristic,
    deleted,
    deleted_at,
    created_at,
    updated_at
) VALUES
-- 1. Rex #1 – Labrador, Charity A (active)
('Rex',
 'Labrador Retriever',
 'Charity A',
 'B001',
 'MALE',
 '2018-05-10',
 '2020-01-01',
 'IN_SERVICE',
 NULL,
 NULL,
 'Calm and friendly',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 2. Rex #2 – same name, different breed & supplier (to test name filter)
('Rex',
 'German Shepherd',
 'Charity B',
 'B002',
 'MALE',
 '2019-04-20',
 '2021-03-12',
 'IN_TRAINING',
 NULL,
 NULL,
 'Strong and attentive',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 3. Max – German Shepherd, Charity A
('Max',
 'German Shepherd',
 'Charity A',
 'B003',
 'MALE',
 '2017-11-01',
 '2019-06-20',
 'IN_SERVICE',
 NULL,
 NULL,
 'Alert and focused',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 4. Bella – Shepherd, retired & re-housed, Charity C
('Bella',
 'German Shepherd',
 'Charity C',
 'B004',
 'FEMALE',
 '2016-09-05',
 '2018-03-11',
 'RETIRED',
 '2024-01-01',
 'RETIRED_REHOUSED',
 'Gentle and calm',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 5. Luna – Spaniel, Charity B
('Luna',
 'Springer Spaniel',
 'Charity B',
 'B005',
 'FEMALE',
 '2020-02-02',
 '2022-04-15',
 'IN_TRAINING',
 NULL,
 NULL,
 'Very playful',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 6. Thor – deleted dog, Doberman, Charity A (left & re-housed)
('Thor',
 'Doberman Pinscher',
 'Charity A',
 'B006',
 'MALE',
 '2018-08-08',
 '2020-05-01',
 'LEFT',
 '2023-02-02',
 'RETIRED_REHOUSED',
 'Strong and alert',
 TRUE,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 7. Shadow – Border Collie, Charity A
('Shadow',
 'Border Collie',
 'Charity A',
 'B007',
 'MALE',
 '2019-01-01',
 '2020-08-20',
 'IN_SERVICE',
 NULL,
 NULL,
 'Very intelligent',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 8. Milo – Labrador, Charity C
('Milo',
 'Labrador Retriever',
 'Charity C',
 'B008',
 'MALE',
 '2021-05-06',
 '2022-01-15',
 'IN_TRAINING',
 NULL,
 NULL,
 'Excitable',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 9. Lexa – deleted Labrador, Charity A (left & re-housed)
('Lexa',
 'Labrador Retriever',
 'Charity A',
 'B009',
 'FEMALE',
 '2017-03-10',
 '2019-02-02',
 'LEFT',
 '2021-06-01',
 'RETIRED_REHOUSED',
 'Obedient',
 TRUE,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),

-- 10. Rocky – young Shepherd, Charity B
('Rocky',
 'German Shepherd',
 'Charity B',
 'B010',
 'MALE',
 '2022-01-01',
 '2023-01-01',
 'IN_TRAINING',
 NULL,
 NULL,
 'Young and energetic',
 FALSE,
 NULL,
 CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP);