create table dogs (
  id bigint generated by default as identity primary key,

  name varchar(255) not null,
  breed varchar(255),
  supplier varchar(255),
  badge_id varchar(64),

  gender varchar(32),
  birth_date date,
  date_acquired date,

  current_status varchar(64),
  leaving_date date,
  leaving_reason varchar(64),

  kennelling_characteristic varchar(512),

  deleted boolean not null default false,
  deleted_at timestamp null,

  created_at timestamp not null,
  updated_at timestamp not null
);